# Generated by Django 4.1.13 on 2024-07-10 08:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('explore', '0002_wisdom_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdom',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
