# Generated by Django 4.1.13 on 2024-07-10 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0003_wisdom_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisdom',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
