# Generated by Django 4.2 on 2024-08-08 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0005_alter_wisdom_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdom',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_wisdoms', to=settings.AUTH_USER_MODEL),
        ),
    ]
